<<<<<<< HEAD

sts: webservers
=======
---
- hosts: webservers
>>>>>>> c35220d7fccd130120b50cd587f3f14f5eb3b6db
  become: True
  tasks:
    - name: install packages
      yum:
        name: httpd
        state: present
    - name: start apache server
      service:
        name: httpd
        state: started
    - name: deploy static website
      copy: 
        src: index.html
        dest: /var/www/html/
