---
- hosts: webservers
  become: true
  gather_facts: yes
  tasks:
  - name: installing httpd server
    yum:
      name: httpd
      state: present
    service:
      name: httpd
      state: started
